[general]
import = ["~/.config/alacritty/base16-circus-256.toml"]

[cursor.style]
blinking = "Never"

[font]
builtin_box_drawing = true
size = 16.0

[font.normal]
# family = "Hurmit Nerd Font"
# family = "Monofur Nerd Font"
# family = "Anonymous Pro"
family = "Iosevka Nerd Font"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Space"
mods = "Shift|Control"

[mouse]
hide_when_typing = true

[window.padding]
x = 8
y = 8

[keyboard]
